SELECT * FROM BOOKS;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS ORDER BY;

--BASIC QUERIES

--1) Retrieve all books in the "Fiction" genre

SELECT * FROM BOOKS
WHERE GENRE='Fiction';

--2) Find books published after the year 1950

SELECT * FROM BOOKS
WHERE PUBLISHED_YEAR>1950;

--3) List all customers from the Canada

SELECT NAME FROM CUSTOMERS
WHERE COUNTRY='Canada';

--4) Show orders placed in November 2023

SELECT * FROM ORDERS
WHERE ORDER_DATE BETWEEN '2023-11-01' AND '2023-11-30';

--5) Retrieve the total stock of books available

SELECT SUM(STOCK) AS TOTAL_STOCK FROM BOOKS;

--6) Find the details of the most expensive book

SELECT * FROM BOOKS
WHERE PRICE=(SELECT MAX(PRICE) FROM BOOKS);

--7) Show all customers who ordered more than 1 quantity of a book

SELECT DISTINCT C.CUSTOMER_ID AS C_ID, C.NAME AS NAME
FROM ORDERS O,CUSTOMERS C
WHERE C.CUSTOMER_ID=O.CUSTOMER_ID AND QUANTITY>1
ORDER BY NAME;

--8) Retrieve all orders where the total amount exceeds $20

SELECT * FROM ORDERS
WHERE TOTAL_AMOUNT>20;

--9) List all genres available in the Books table

SELECT DISTINCT GENRE FROM BOOKS;

--10) Find the book with the lowest stock

SELECT * FROM BOOKS
WHERE STOCK=(SELECT MIN(STOCK) FROM BOOKS);

--11) Calculate the total revenue generated from all orders

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS;

--ADVANACE QUERIES

--1) Retrieve the total number of books sold for each genre

SELECT GENRE,SUM(O.QUANTITY) AS TOTAL_BOOKS_SOLD
FROM BOOKS B JOIN
ORDERS O
ON B.BOOK_ID=O.BOOK_ID
GROUP BY GENRE;

--2) Find the average price of books in the "Fantasy" genre

SELECT AVG(PRICE) AS AVERAGE_PRICE
FROM BOOKS
WHERE GENRE='Fantasy';

--3) List customers who have placed at least 2 orders

SELECT DISTINCT C.CUSTOMER_ID,C.NAME,COUNT(O.ORDER_ID) AS ORDER_COUNT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.NAME
HAVING COUNT(O.ORDER_ID)>=2
ORDER BY C.NAME;

--4) Find the most frequently ordered book

WITH ranked_orders AS (
    SELECT b.book_id, 
           b.title, 
           COUNT(o.order_id) AS order_frequency,
           RANK() OVER (ORDER BY COUNT(o.order_id) DESC) as rnk
    FROM books b
    JOIN orders o ON b.book_id = o.book_id
    GROUP BY b.book_id, b.title
)
SELECT book_id, title, order_frequency
FROM ranked_orders
WHERE rnk = 1;

--5) Show the top 3 most expensive books of 'Fantasy' Genre 

SELECT book_id, title, price
FROM (
    SELECT book_id, title, price,
           DENSE_RANK() OVER (ORDER BY price DESC) as price_rank
    FROM books
    WHERE genre = 'Fantasy'
) ranked_books
WHERE price_rank <= 3;

--6) Retrieve the total quantity of books sold by each author

SELECT B.AUTHOR,SUM(O.QUANTITY) AS TOTAL_BOOKS_SOLD
FROM BOOKS B
JOIN ORDERS O
ON B.BOOK_ID=O.BOOK_ID
GROUP BY B.AUTHOR
ORDER BY B.AUTHOR;

--7) List the cities where customers spent over $30 are located

SELECT C.CITY, SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY
HAVING SUM(O.TOTAL_AMOUNT)>30
ORDER BY C.CITY;

--8) Find the customer who spent the most on orders

SELECT C.CUSTOMER_ID,C.NAME,SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.NAME
HAVING SUM(O.TOTAL_AMOUNT)=(SELECT SUM(TOTAL_AMOUNT) FROM ORDERS
							 GROUP BY CUSTOMER_ID
							 ORDER BY SUM(TOTAL_AMOUNT) DESC
							 LIMIT 1);

--9) Calculate the stock remaining after fulfilling all orders

SELECT B.BOOK_ID, B.TITLE, B.STOCK, SUM(O.QUANTITY) AS SOLD_OUT, (B.STOCK - COALESCE(SUM(O.QUANTITY),0)) AS REMAINING_STOCK
FROM BOOKS B LEFT JOIN ORDERS O
ON B.BOOK_ID=O.BOOK_ID
GROUP BY B.BOOK_ID
ORDER BY REMAINING_STOCK DESC;

--10) Find all customers who placed at least one order in the last 6 months of 2023,
--and calculate their average order value. 
--Sort the results from the highest average order value to the lowest

SELECT C.NAME,C.CUSTOMER_ID, COUNT(O.ORDER_ID), AVG(O.TOTAL_AMOUNT) AS AVG_ORDER_VALUE
FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE ORDER_DATE BETWEEN '01-07-2023' AND '31-12-2023'
GROUP BY C.NAME,C.CUSTOMER_ID
ORDER BY AVG_ORDER_VALUE DESC;

--11)Find all genres where the average price of a book is greater than $25,
--but the total number of books sold in that genre is less than 400.
--Display the genre name, the total revenue generated by that genre,
--and label the genre's status as 'Needs Marketing'.

SELECT B.GENRE, AVG(B.PRICE) AS AVG_PRICE, SUM(O.QUANTITY) AS TOTAL_BOOKS_SOLD,
		SUM(O.QUANTITY*B.PRICE) AS TOTAL_REVENUE_GENERATED, 'NEEDS MARKETING' AS STATUS
FROM BOOKS B JOIN ORDERS O
ON B.BOOK_ID=O.BOOK_ID
GROUP BY B.GENRE
HAVING AVG(B.PRICE)>25 AND SUM(O.QUANTITY)<400;